OUTPUT_DIR: "./exp_cuhk"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "/mnt/workspace/workgroup/mohe/datasets/ps/cuhk_sysu"
  BATCH_SIZE_TRAIN: 8
SOLVER:
  MAX_EPOCHS: 20
  LR_DECAY_MILESTONES: [1e5]
MODEL:
  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000
