OUTPUT_DIR: "./exp_cuhk"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "/root/autodl-tmp/datasets/ps/cuhk_sysu"
  BATCH_SIZE_TRAIN: 12
  NUM_WORKERS_TRAIN: 8
SOLVER:
  MAX_EPOCHS: 25
  BASE_LR: 0.006
MODEL:
  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000