OUTPUT_DIR: "./exp_cuhk"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "/root/autodl-tmp/datasets/ps/cuhk_sysu"
  BATCH_SIZE_TRAIN: 4
SOLVER:
  MAX_EPOCHS: 20
  LR_DECAY_MILESTONES: [16]
MODEL:
  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000
