OUTPUT_DIR: "./exp_mvn"
INPUT:
  DATASET: "MVN"
  BATCH_SIZE_TRAIN: 3
  MIN_SIZE: 900
  MAX_SIZE: 1500
SOLVER:
  MAX_EPOCHS: 30
  LR_DECAY_MILESTONES: [20]
MODEL:
  LOSS:
    LUT_SIZE: 3087
    CQ_SIZE: 3000
