OUTPUT_DIR: "./exp_mvn"
INPUT:
  DATASET: "MVN"
  DATA_ROOT: "/mnt/workspace/workgroup/mohe/datasets/ps/mvn_cuhk"
  BATCH_SIZE_TRAIN: 32
  MIN_SIZE: 240
  MAX_SIZE: 720
SOLVER:
  MAX_EPOCHS: 18
  LR_DECAY_MILESTONES: [1e5]
MODEL:
  LOSS:
    LUT_SIZE: 3087
    CQ_SIZE: 3000
