OUTPUT_DIR: "./exp_mvn_pretrain"
INPUT:
  DATASET: "MVN_pretrain"
  DATA_ROOT: "/mnt/workspace/workgroup/mohe/datasets/ps/mvn"
  BATCH_SIZE_TRAIN: 32
  MIN_SIZE: 240
  MAX_SIZE: 720
SOLVER:
  MAX_EPOCHS: 10
  LR_DECAY_MILESTONES: [1e5]
MODEL:
  LOSS:
    LUT_SIZE: 3087
    CQ_SIZE: 3000
