OUTPUT_DIR: "./exp_prw"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "/mnt/workspace/workgroup/mohe/datasets/ps/prw"
  BATCH_SIZE_TRAIN: 8
SOLVER:
  MAX_EPOCHS: 20
  LR_DECAY_MILESTONES: [1e5]
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
