OUTPUT_DIR: "./exp_prw"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "/root/autodl-tmp/datasets/ps/prw"
  BATCH_SIZE_TRAIN: 5
SOLVER:
  MAX_EPOCHS: 18
  LR_DECAY_MILESTONES: [13]
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
