OUTPUT_DIR: "./exp_prw"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "/root/autodl-tmp/datasets/ps/prw"
  BATCH_SIZE_TRAIN: 5
  NUM_WORKERS_TRAIN: 5
SOLVER:
  MAX_EPOCHS: 25
  BASE_LR: 0.003
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
